<!-- @@@@@@@@@@@@@@@@@@@@@@     Footer            @@@@@@@@@@@@@@@@@@@@@@@@@@ -->
<footer>
    <p>Web site not designed by <del>Robert M. Erickson.</del></p>
    <p>Web site generated by infinite monkeys with infinite typewriters</p>
</footer>
<!-- @@@@@@@@@@@@@@@@@@@@ Ends Footer             @@@@@@@@@@@@@@@@@@@@@@@@@@ -->

</body>
</html>